    # plot_execution_time_log_scale(df , search)
    # plot_basic_operations(df, search)
    # plot_solution_quality(df, search)
    # plot_time_vs_density(df, search)
    # plot_time_vs_vertices(df, search)